// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gridWorld.proto

#include "gridWorld.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_gridWorld_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_gridWorld_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_State;
}  // namespace protobuf_gridWorld_2eproto
namespace Message {
namespace GridWorld {
class InitResDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<InitRes>
      _instance;
} _InitRes_default_instance_;
class StateDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<State>
      _instance;
} _State_default_instance_;
class StepResDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<StepRes>
      _instance;
} _StepRes_default_instance_;
class ResetResDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ResetRes>
      _instance;
} _ResetRes_default_instance_;
class RenderReqDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<RenderReq>
      _instance;
} _RenderReq_default_instance_;
}  // namespace GridWorld
}  // namespace Message
namespace protobuf_gridWorld_2eproto {
static void InitDefaultsInitRes() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Message::GridWorld::_InitRes_default_instance_;
    new (ptr) ::Message::GridWorld::InitRes();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Message::GridWorld::InitRes::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_InitRes =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsInitRes}, {}};

static void InitDefaultsState() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Message::GridWorld::_State_default_instance_;
    new (ptr) ::Message::GridWorld::State();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Message::GridWorld::State::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_State =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsState}, {}};

static void InitDefaultsStepRes() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Message::GridWorld::_StepRes_default_instance_;
    new (ptr) ::Message::GridWorld::StepRes();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Message::GridWorld::StepRes::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_StepRes =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsStepRes}, {
      &protobuf_gridWorld_2eproto::scc_info_State.base,}};

static void InitDefaultsResetRes() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Message::GridWorld::_ResetRes_default_instance_;
    new (ptr) ::Message::GridWorld::ResetRes();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Message::GridWorld::ResetRes::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_ResetRes =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsResetRes}, {
      &protobuf_gridWorld_2eproto::scc_info_State.base,}};

static void InitDefaultsRenderReq() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Message::GridWorld::_RenderReq_default_instance_;
    new (ptr) ::Message::GridWorld::RenderReq();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Message::GridWorld::RenderReq::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_RenderReq =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsRenderReq}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_InitRes.base);
  ::google::protobuf::internal::InitSCC(&scc_info_State.base);
  ::google::protobuf::internal::InitSCC(&scc_info_StepRes.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ResetRes.base);
  ::google::protobuf::internal::InitSCC(&scc_info_RenderReq.base);
}

::google::protobuf::Metadata file_level_metadata[5];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::GridWorld::InitRes, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::GridWorld::InitRes, max_row_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::GridWorld::InitRes, max_col_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::GridWorld::InitRes, num_action_space_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::GridWorld::InitRes, map_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::GridWorld::State, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::GridWorld::State, index_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::GridWorld::StepRes, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::GridWorld::StepRes, done_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::GridWorld::StepRes, reward_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::GridWorld::StepRes, next_state_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::GridWorld::ResetRes, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::GridWorld::ResetRes, next_state_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::GridWorld::RenderReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::GridWorld::RenderReq, q_table_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Message::GridWorld::InitRes)},
  { 9, -1, sizeof(::Message::GridWorld::State)},
  { 15, -1, sizeof(::Message::GridWorld::StepRes)},
  { 23, -1, sizeof(::Message::GridWorld::ResetRes)},
  { 29, -1, sizeof(::Message::GridWorld::RenderReq)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::Message::GridWorld::_InitRes_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::Message::GridWorld::_State_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::Message::GridWorld::_StepRes_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::Message::GridWorld::_ResetRes_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::Message::GridWorld::_RenderReq_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "gridWorld.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 5);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\017gridWorld.proto\022\021Message.GridWorld\"R\n\007"
      "InitRes\022\017\n\007max_row\030\001 \001(\005\022\017\n\007max_col\030\002 \001("
      "\005\022\030\n\020num_action_space\030\003 \001(\005\022\013\n\003map\030\004 \001(\t"
      "\"\026\n\005State\022\r\n\005index\030\001 \001(\t\"U\n\007StepRes\022\014\n\004d"
      "one\030\001 \001(\005\022\016\n\006reward\030\002 \001(\002\022,\n\nnext_state\030"
      "\003 \001(\0132\030.Message.GridWorld.State\"8\n\010Reset"
      "Res\022,\n\nnext_state\030\001 \001(\0132\030.Message.GridWo"
      "rld.State\"\034\n\tRenderReq\022\017\n\007q_table\030\001 \003(\002b"
      "\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 327);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "gridWorld.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_gridWorld_2eproto
namespace Message {
namespace GridWorld {

// ===================================================================

void InitRes::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int InitRes::kMaxRowFieldNumber;
const int InitRes::kMaxColFieldNumber;
const int InitRes::kNumActionSpaceFieldNumber;
const int InitRes::kMapFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

InitRes::InitRes()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_gridWorld_2eproto::scc_info_InitRes.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Message.GridWorld.InitRes)
}
InitRes::InitRes(const InitRes& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  map_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.map().size() > 0) {
    map_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.map_);
  }
  ::memcpy(&max_row_, &from.max_row_,
    static_cast<size_t>(reinterpret_cast<char*>(&num_action_space_) -
    reinterpret_cast<char*>(&max_row_)) + sizeof(num_action_space_));
  // @@protoc_insertion_point(copy_constructor:Message.GridWorld.InitRes)
}

void InitRes::SharedCtor() {
  map_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&max_row_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&num_action_space_) -
      reinterpret_cast<char*>(&max_row_)) + sizeof(num_action_space_));
}

InitRes::~InitRes() {
  // @@protoc_insertion_point(destructor:Message.GridWorld.InitRes)
  SharedDtor();
}

void InitRes::SharedDtor() {
  map_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void InitRes::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* InitRes::descriptor() {
  ::protobuf_gridWorld_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_gridWorld_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const InitRes& InitRes::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_gridWorld_2eproto::scc_info_InitRes.base);
  return *internal_default_instance();
}


void InitRes::Clear() {
// @@protoc_insertion_point(message_clear_start:Message.GridWorld.InitRes)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  map_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&max_row_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&num_action_space_) -
      reinterpret_cast<char*>(&max_row_)) + sizeof(num_action_space_));
  _internal_metadata_.Clear();
}

bool InitRes::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Message.GridWorld.InitRes)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 max_row = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &max_row_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 max_col = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &max_col_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 num_action_space = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &num_action_space_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string map = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_map()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->map().data(), static_cast<int>(this->map().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Message.GridWorld.InitRes.map"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Message.GridWorld.InitRes)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Message.GridWorld.InitRes)
  return false;
#undef DO_
}

void InitRes::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Message.GridWorld.InitRes)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 max_row = 1;
  if (this->max_row() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->max_row(), output);
  }

  // int32 max_col = 2;
  if (this->max_col() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->max_col(), output);
  }

  // int32 num_action_space = 3;
  if (this->num_action_space() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->num_action_space(), output);
  }

  // string map = 4;
  if (this->map().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->map().data(), static_cast<int>(this->map().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Message.GridWorld.InitRes.map");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->map(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Message.GridWorld.InitRes)
}

::google::protobuf::uint8* InitRes::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Message.GridWorld.InitRes)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 max_row = 1;
  if (this->max_row() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->max_row(), target);
  }

  // int32 max_col = 2;
  if (this->max_col() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->max_col(), target);
  }

  // int32 num_action_space = 3;
  if (this->num_action_space() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->num_action_space(), target);
  }

  // string map = 4;
  if (this->map().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->map().data(), static_cast<int>(this->map().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Message.GridWorld.InitRes.map");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->map(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Message.GridWorld.InitRes)
  return target;
}

size_t InitRes::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Message.GridWorld.InitRes)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string map = 4;
  if (this->map().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->map());
  }

  // int32 max_row = 1;
  if (this->max_row() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->max_row());
  }

  // int32 max_col = 2;
  if (this->max_col() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->max_col());
  }

  // int32 num_action_space = 3;
  if (this->num_action_space() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->num_action_space());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void InitRes::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Message.GridWorld.InitRes)
  GOOGLE_DCHECK_NE(&from, this);
  const InitRes* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const InitRes>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Message.GridWorld.InitRes)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Message.GridWorld.InitRes)
    MergeFrom(*source);
  }
}

void InitRes::MergeFrom(const InitRes& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Message.GridWorld.InitRes)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.map().size() > 0) {

    map_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.map_);
  }
  if (from.max_row() != 0) {
    set_max_row(from.max_row());
  }
  if (from.max_col() != 0) {
    set_max_col(from.max_col());
  }
  if (from.num_action_space() != 0) {
    set_num_action_space(from.num_action_space());
  }
}

void InitRes::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Message.GridWorld.InitRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void InitRes::CopyFrom(const InitRes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Message.GridWorld.InitRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InitRes::IsInitialized() const {
  return true;
}

void InitRes::Swap(InitRes* other) {
  if (other == this) return;
  InternalSwap(other);
}
void InitRes::InternalSwap(InitRes* other) {
  using std::swap;
  map_.Swap(&other->map_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(max_row_, other->max_row_);
  swap(max_col_, other->max_col_);
  swap(num_action_space_, other->num_action_space_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata InitRes::GetMetadata() const {
  protobuf_gridWorld_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_gridWorld_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void State::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int State::kIndexFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

State::State()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_gridWorld_2eproto::scc_info_State.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Message.GridWorld.State)
}
State::State(const State& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  index_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.index().size() > 0) {
    index_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.index_);
  }
  // @@protoc_insertion_point(copy_constructor:Message.GridWorld.State)
}

void State::SharedCtor() {
  index_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

State::~State() {
  // @@protoc_insertion_point(destructor:Message.GridWorld.State)
  SharedDtor();
}

void State::SharedDtor() {
  index_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void State::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* State::descriptor() {
  ::protobuf_gridWorld_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_gridWorld_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const State& State::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_gridWorld_2eproto::scc_info_State.base);
  return *internal_default_instance();
}


void State::Clear() {
// @@protoc_insertion_point(message_clear_start:Message.GridWorld.State)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  index_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool State::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Message.GridWorld.State)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string index = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_index()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->index().data(), static_cast<int>(this->index().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Message.GridWorld.State.index"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Message.GridWorld.State)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Message.GridWorld.State)
  return false;
#undef DO_
}

void State::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Message.GridWorld.State)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string index = 1;
  if (this->index().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->index().data(), static_cast<int>(this->index().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Message.GridWorld.State.index");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->index(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Message.GridWorld.State)
}

::google::protobuf::uint8* State::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Message.GridWorld.State)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string index = 1;
  if (this->index().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->index().data(), static_cast<int>(this->index().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Message.GridWorld.State.index");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->index(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Message.GridWorld.State)
  return target;
}

size_t State::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Message.GridWorld.State)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string index = 1;
  if (this->index().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->index());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void State::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Message.GridWorld.State)
  GOOGLE_DCHECK_NE(&from, this);
  const State* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const State>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Message.GridWorld.State)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Message.GridWorld.State)
    MergeFrom(*source);
  }
}

void State::MergeFrom(const State& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Message.GridWorld.State)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.index().size() > 0) {

    index_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.index_);
  }
}

void State::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Message.GridWorld.State)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void State::CopyFrom(const State& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Message.GridWorld.State)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool State::IsInitialized() const {
  return true;
}

void State::Swap(State* other) {
  if (other == this) return;
  InternalSwap(other);
}
void State::InternalSwap(State* other) {
  using std::swap;
  index_.Swap(&other->index_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata State::GetMetadata() const {
  protobuf_gridWorld_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_gridWorld_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void StepRes::InitAsDefaultInstance() {
  ::Message::GridWorld::_StepRes_default_instance_._instance.get_mutable()->next_state_ = const_cast< ::Message::GridWorld::State*>(
      ::Message::GridWorld::State::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int StepRes::kDoneFieldNumber;
const int StepRes::kRewardFieldNumber;
const int StepRes::kNextStateFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

StepRes::StepRes()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_gridWorld_2eproto::scc_info_StepRes.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Message.GridWorld.StepRes)
}
StepRes::StepRes(const StepRes& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_next_state()) {
    next_state_ = new ::Message::GridWorld::State(*from.next_state_);
  } else {
    next_state_ = NULL;
  }
  ::memcpy(&done_, &from.done_,
    static_cast<size_t>(reinterpret_cast<char*>(&reward_) -
    reinterpret_cast<char*>(&done_)) + sizeof(reward_));
  // @@protoc_insertion_point(copy_constructor:Message.GridWorld.StepRes)
}

void StepRes::SharedCtor() {
  ::memset(&next_state_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&reward_) -
      reinterpret_cast<char*>(&next_state_)) + sizeof(reward_));
}

StepRes::~StepRes() {
  // @@protoc_insertion_point(destructor:Message.GridWorld.StepRes)
  SharedDtor();
}

void StepRes::SharedDtor() {
  if (this != internal_default_instance()) delete next_state_;
}

void StepRes::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* StepRes::descriptor() {
  ::protobuf_gridWorld_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_gridWorld_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const StepRes& StepRes::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_gridWorld_2eproto::scc_info_StepRes.base);
  return *internal_default_instance();
}


void StepRes::Clear() {
// @@protoc_insertion_point(message_clear_start:Message.GridWorld.StepRes)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && next_state_ != NULL) {
    delete next_state_;
  }
  next_state_ = NULL;
  ::memset(&done_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&reward_) -
      reinterpret_cast<char*>(&done_)) + sizeof(reward_));
  _internal_metadata_.Clear();
}

bool StepRes::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Message.GridWorld.StepRes)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 done = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &done_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float reward = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(21u /* 21 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &reward_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .Message.GridWorld.State next_state = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_next_state()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Message.GridWorld.StepRes)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Message.GridWorld.StepRes)
  return false;
#undef DO_
}

void StepRes::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Message.GridWorld.StepRes)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 done = 1;
  if (this->done() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->done(), output);
  }

  // float reward = 2;
  if (this->reward() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->reward(), output);
  }

  // .Message.GridWorld.State next_state = 3;
  if (this->has_next_state()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->_internal_next_state(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Message.GridWorld.StepRes)
}

::google::protobuf::uint8* StepRes::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Message.GridWorld.StepRes)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 done = 1;
  if (this->done() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->done(), target);
  }

  // float reward = 2;
  if (this->reward() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->reward(), target);
  }

  // .Message.GridWorld.State next_state = 3;
  if (this->has_next_state()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, this->_internal_next_state(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Message.GridWorld.StepRes)
  return target;
}

size_t StepRes::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Message.GridWorld.StepRes)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .Message.GridWorld.State next_state = 3;
  if (this->has_next_state()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *next_state_);
  }

  // int32 done = 1;
  if (this->done() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->done());
  }

  // float reward = 2;
  if (this->reward() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void StepRes::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Message.GridWorld.StepRes)
  GOOGLE_DCHECK_NE(&from, this);
  const StepRes* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const StepRes>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Message.GridWorld.StepRes)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Message.GridWorld.StepRes)
    MergeFrom(*source);
  }
}

void StepRes::MergeFrom(const StepRes& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Message.GridWorld.StepRes)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_next_state()) {
    mutable_next_state()->::Message::GridWorld::State::MergeFrom(from.next_state());
  }
  if (from.done() != 0) {
    set_done(from.done());
  }
  if (from.reward() != 0) {
    set_reward(from.reward());
  }
}

void StepRes::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Message.GridWorld.StepRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StepRes::CopyFrom(const StepRes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Message.GridWorld.StepRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StepRes::IsInitialized() const {
  return true;
}

void StepRes::Swap(StepRes* other) {
  if (other == this) return;
  InternalSwap(other);
}
void StepRes::InternalSwap(StepRes* other) {
  using std::swap;
  swap(next_state_, other->next_state_);
  swap(done_, other->done_);
  swap(reward_, other->reward_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata StepRes::GetMetadata() const {
  protobuf_gridWorld_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_gridWorld_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ResetRes::InitAsDefaultInstance() {
  ::Message::GridWorld::_ResetRes_default_instance_._instance.get_mutable()->next_state_ = const_cast< ::Message::GridWorld::State*>(
      ::Message::GridWorld::State::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ResetRes::kNextStateFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ResetRes::ResetRes()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_gridWorld_2eproto::scc_info_ResetRes.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Message.GridWorld.ResetRes)
}
ResetRes::ResetRes(const ResetRes& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_next_state()) {
    next_state_ = new ::Message::GridWorld::State(*from.next_state_);
  } else {
    next_state_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:Message.GridWorld.ResetRes)
}

void ResetRes::SharedCtor() {
  next_state_ = NULL;
}

ResetRes::~ResetRes() {
  // @@protoc_insertion_point(destructor:Message.GridWorld.ResetRes)
  SharedDtor();
}

void ResetRes::SharedDtor() {
  if (this != internal_default_instance()) delete next_state_;
}

void ResetRes::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ResetRes::descriptor() {
  ::protobuf_gridWorld_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_gridWorld_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ResetRes& ResetRes::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_gridWorld_2eproto::scc_info_ResetRes.base);
  return *internal_default_instance();
}


void ResetRes::Clear() {
// @@protoc_insertion_point(message_clear_start:Message.GridWorld.ResetRes)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && next_state_ != NULL) {
    delete next_state_;
  }
  next_state_ = NULL;
  _internal_metadata_.Clear();
}

bool ResetRes::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Message.GridWorld.ResetRes)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .Message.GridWorld.State next_state = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_next_state()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Message.GridWorld.ResetRes)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Message.GridWorld.ResetRes)
  return false;
#undef DO_
}

void ResetRes::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Message.GridWorld.ResetRes)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .Message.GridWorld.State next_state = 1;
  if (this->has_next_state()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_next_state(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Message.GridWorld.ResetRes)
}

::google::protobuf::uint8* ResetRes::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Message.GridWorld.ResetRes)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .Message.GridWorld.State next_state = 1;
  if (this->has_next_state()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_next_state(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Message.GridWorld.ResetRes)
  return target;
}

size_t ResetRes::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Message.GridWorld.ResetRes)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .Message.GridWorld.State next_state = 1;
  if (this->has_next_state()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *next_state_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ResetRes::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Message.GridWorld.ResetRes)
  GOOGLE_DCHECK_NE(&from, this);
  const ResetRes* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ResetRes>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Message.GridWorld.ResetRes)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Message.GridWorld.ResetRes)
    MergeFrom(*source);
  }
}

void ResetRes::MergeFrom(const ResetRes& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Message.GridWorld.ResetRes)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_next_state()) {
    mutable_next_state()->::Message::GridWorld::State::MergeFrom(from.next_state());
  }
}

void ResetRes::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Message.GridWorld.ResetRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ResetRes::CopyFrom(const ResetRes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Message.GridWorld.ResetRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResetRes::IsInitialized() const {
  return true;
}

void ResetRes::Swap(ResetRes* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ResetRes::InternalSwap(ResetRes* other) {
  using std::swap;
  swap(next_state_, other->next_state_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ResetRes::GetMetadata() const {
  protobuf_gridWorld_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_gridWorld_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void RenderReq::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RenderReq::kQTableFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RenderReq::RenderReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_gridWorld_2eproto::scc_info_RenderReq.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Message.GridWorld.RenderReq)
}
RenderReq::RenderReq(const RenderReq& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      q_table_(from.q_table_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Message.GridWorld.RenderReq)
}

void RenderReq::SharedCtor() {
}

RenderReq::~RenderReq() {
  // @@protoc_insertion_point(destructor:Message.GridWorld.RenderReq)
  SharedDtor();
}

void RenderReq::SharedDtor() {
}

void RenderReq::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* RenderReq::descriptor() {
  ::protobuf_gridWorld_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_gridWorld_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const RenderReq& RenderReq::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_gridWorld_2eproto::scc_info_RenderReq.base);
  return *internal_default_instance();
}


void RenderReq::Clear() {
// @@protoc_insertion_point(message_clear_start:Message.GridWorld.RenderReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  q_table_.Clear();
  _internal_metadata_.Clear();
}

bool RenderReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Message.GridWorld.RenderReq)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated float q_table = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_q_table())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(13u /* 13 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 10u, input, this->mutable_q_table())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Message.GridWorld.RenderReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Message.GridWorld.RenderReq)
  return false;
#undef DO_
}

void RenderReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Message.GridWorld.RenderReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float q_table = 1;
  if (this->q_table_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(1, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _q_table_cached_byte_size_));
    ::google::protobuf::internal::WireFormatLite::WriteFloatArray(
      this->q_table().data(), this->q_table_size(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Message.GridWorld.RenderReq)
}

::google::protobuf::uint8* RenderReq::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Message.GridWorld.RenderReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float q_table = 1;
  if (this->q_table_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      1,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _q_table_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatNoTagToArray(this->q_table_, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Message.GridWorld.RenderReq)
  return target;
}

size_t RenderReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Message.GridWorld.RenderReq)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated float q_table = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->q_table_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _q_table_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RenderReq::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Message.GridWorld.RenderReq)
  GOOGLE_DCHECK_NE(&from, this);
  const RenderReq* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const RenderReq>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Message.GridWorld.RenderReq)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Message.GridWorld.RenderReq)
    MergeFrom(*source);
  }
}

void RenderReq::MergeFrom(const RenderReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Message.GridWorld.RenderReq)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  q_table_.MergeFrom(from.q_table_);
}

void RenderReq::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Message.GridWorld.RenderReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RenderReq::CopyFrom(const RenderReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Message.GridWorld.RenderReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RenderReq::IsInitialized() const {
  return true;
}

void RenderReq::Swap(RenderReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RenderReq::InternalSwap(RenderReq* other) {
  using std::swap;
  q_table_.InternalSwap(&other->q_table_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata RenderReq::GetMetadata() const {
  protobuf_gridWorld_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_gridWorld_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace GridWorld
}  // namespace Message
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Message::GridWorld::InitRes* Arena::CreateMaybeMessage< ::Message::GridWorld::InitRes >(Arena* arena) {
  return Arena::CreateInternal< ::Message::GridWorld::InitRes >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Message::GridWorld::State* Arena::CreateMaybeMessage< ::Message::GridWorld::State >(Arena* arena) {
  return Arena::CreateInternal< ::Message::GridWorld::State >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Message::GridWorld::StepRes* Arena::CreateMaybeMessage< ::Message::GridWorld::StepRes >(Arena* arena) {
  return Arena::CreateInternal< ::Message::GridWorld::StepRes >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Message::GridWorld::ResetRes* Arena::CreateMaybeMessage< ::Message::GridWorld::ResetRes >(Arena* arena) {
  return Arena::CreateInternal< ::Message::GridWorld::ResetRes >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Message::GridWorld::RenderReq* Arena::CreateMaybeMessage< ::Message::GridWorld::RenderReq >(Arena* arena) {
  return Arena::CreateInternal< ::Message::GridWorld::RenderReq >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
