# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gridWorld.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gridWorld.proto',
  package='Message.GridWorld',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fgridWorld.proto\x12\x11Message.GridWorld\"R\n\x07InitRes\x12\x0f\n\x07max_row\x18\x01 \x01(\x05\x12\x0f\n\x07max_col\x18\x02 \x01(\x05\x12\x18\n\x10num_action_space\x18\x03 \x01(\x05\x12\x0b\n\x03map\x18\x04 \x01(\t\"\x16\n\x05State\x12\r\n\x05index\x18\x01 \x01(\t\"U\n\x07StepRes\x12\x0c\n\x04\x64one\x18\x01 \x01(\x05\x12\x0e\n\x06reward\x18\x02 \x01(\x02\x12,\n\nnext_state\x18\x03 \x01(\x0b\x32\x18.Message.GridWorld.State\"8\n\x08ResetRes\x12,\n\nnext_state\x18\x01 \x01(\x0b\x32\x18.Message.GridWorld.State\"\x1c\n\tRenderReq\x12\x0f\n\x07q_table\x18\x01 \x03(\x02\x62\x06proto3')
)




_INITRES = _descriptor.Descriptor(
  name='InitRes',
  full_name='Message.GridWorld.InitRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_row', full_name='Message.GridWorld.InitRes.max_row', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_col', full_name='Message.GridWorld.InitRes.max_col', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_action_space', full_name='Message.GridWorld.InitRes.num_action_space', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='map', full_name='Message.GridWorld.InitRes.map', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=120,
)


_STATE = _descriptor.Descriptor(
  name='State',
  full_name='Message.GridWorld.State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='Message.GridWorld.State.index', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=144,
)


_STEPRES = _descriptor.Descriptor(
  name='StepRes',
  full_name='Message.GridWorld.StepRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='done', full_name='Message.GridWorld.StepRes.done', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reward', full_name='Message.GridWorld.StepRes.reward', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_state', full_name='Message.GridWorld.StepRes.next_state', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=231,
)


_RESETRES = _descriptor.Descriptor(
  name='ResetRes',
  full_name='Message.GridWorld.ResetRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='next_state', full_name='Message.GridWorld.ResetRes.next_state', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=289,
)


_RENDERREQ = _descriptor.Descriptor(
  name='RenderReq',
  full_name='Message.GridWorld.RenderReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='q_table', full_name='Message.GridWorld.RenderReq.q_table', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=319,
)

_STEPRES.fields_by_name['next_state'].message_type = _STATE
_RESETRES.fields_by_name['next_state'].message_type = _STATE
DESCRIPTOR.message_types_by_name['InitRes'] = _INITRES
DESCRIPTOR.message_types_by_name['State'] = _STATE
DESCRIPTOR.message_types_by_name['StepRes'] = _STEPRES
DESCRIPTOR.message_types_by_name['ResetRes'] = _RESETRES
DESCRIPTOR.message_types_by_name['RenderReq'] = _RENDERREQ
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InitRes = _reflection.GeneratedProtocolMessageType('InitRes', (_message.Message,), dict(
  DESCRIPTOR = _INITRES,
  __module__ = 'gridWorld_pb2'
  # @@protoc_insertion_point(class_scope:Message.GridWorld.InitRes)
  ))
_sym_db.RegisterMessage(InitRes)

State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), dict(
  DESCRIPTOR = _STATE,
  __module__ = 'gridWorld_pb2'
  # @@protoc_insertion_point(class_scope:Message.GridWorld.State)
  ))
_sym_db.RegisterMessage(State)

StepRes = _reflection.GeneratedProtocolMessageType('StepRes', (_message.Message,), dict(
  DESCRIPTOR = _STEPRES,
  __module__ = 'gridWorld_pb2'
  # @@protoc_insertion_point(class_scope:Message.GridWorld.StepRes)
  ))
_sym_db.RegisterMessage(StepRes)

ResetRes = _reflection.GeneratedProtocolMessageType('ResetRes', (_message.Message,), dict(
  DESCRIPTOR = _RESETRES,
  __module__ = 'gridWorld_pb2'
  # @@protoc_insertion_point(class_scope:Message.GridWorld.ResetRes)
  ))
_sym_db.RegisterMessage(ResetRes)

RenderReq = _reflection.GeneratedProtocolMessageType('RenderReq', (_message.Message,), dict(
  DESCRIPTOR = _RENDERREQ,
  __module__ = 'gridWorld_pb2'
  # @@protoc_insertion_point(class_scope:Message.GridWorld.RenderReq)
  ))
_sym_db.RegisterMessage(RenderReq)


# @@protoc_insertion_point(module_scope)
